In [1]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1, 2], [3,4]])
print(b)

[[1 2]
 [3 4]]


In [4]:
c = np.array([[1, 2, 3],[2, 3, 4],[3, 4, 5]])
print(c)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [5]:
x = np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
x2 = x*2
print(x2)

[ 2  4  6  8 10 12 14 16 18 20]


In [8]:
print("mean", x.mean())
print("max", x.max())
print("shape", x.shape)

mean 5.5
max 10
shape (10,)
